apiVersion: v1
kind: ConfigMap
metadata:
  name: budibase-nginx-unpriv
data:
  15-openshift.envsh: |
    #!/bin/sh
    # Render to writable /tmp instead of /etc/nginx
    export NGINX_ENVSUBST_OUTPUT_DIR="/tmp"

    # Ensure nginx 'resolver' uses an IP literal (proxy_pass uses variables)
    case "${RESOLVER:-}" in
      ''|*[!0-9.:]*)
        ns="$(awk '/^nameserver/{print $2; exit}' /etc/resolv.conf)"
        if [ -n "$ns" ]; then
          case "$ns" in *:*) ns="[$ns]";; esac
          export RESOLVER="$ns"
        fi
        ;;
    esac

  80-listen-on-ipv6-by-default.sh: |
    #!/bin/sh
    # After envsubst, remove IPv6 listen lines if IPv6 is unavailable.
    set -e
    CONF="/tmp/nginx.conf"
    if [ ! -f /proc/net/if_inet6 ] && [ -f "$CONF" ]; then
      sed -i '/listen  \[::\]/d' "$CONF" || true
      echo "[openshift] IPv6 disabled; removed IPv6 listen lines from $CONF"
    fi

  90-openshift-unprivileged.sh: |
    #!/bin/sh
    # Patch rendered /tmp/nginx.conf for unprivileged runtime and ports.
    set -e
    CONF="/tmp/nginx.conf"

    # Ensure temp dirs exist and are writable
    mkdir -p /tmp/client_temp /tmp/proxy_temp /tmp/fastcgi_temp /tmp/uwsgi_temp /tmp/scgi_temp
    chmod 0777 /tmp/client_temp /tmp/proxy_temp /tmp/fastcgi_temp /tmp/uwsgi_temp /tmp/scgi_temp || true

    if [ -f "$CONF" ]; then
      # pid → /tmp
      if grep -qE '^[[:space:]]*pid[[:space:]]+' "$CONF"; then
        sed -i -E 's|^[[:space:]]*pid[[:space:]]+.*;|pid                     /tmp/nginx.pid;|' "$CONF" || true
      else
        sed -i '1i pid                     /tmp/nginx.pid;' "$CONF" || true
      fi

      # Temp paths inside http { }
      if ! grep -q 'client_body_temp_path /tmp/client_temp;' "$CONF"; then
        sed -i '/http {/a \
        # Temp paths for OpenShift arbitrary UID\
        client_body_temp_path /tmp/client_temp;\
        proxy_temp_path       /tmp/proxy_temp;\
        fastcgi_temp_path     /tmp/fastcgi_temp;\
        uwsgi_temp_path       /tmp/uwsgi_temp;\
        scgi_temp_path        /tmp/scgi_temp;' "$CONF" || true
      fi

      # The status server in Budibase config listens on privileged port 81 → move to 18081
      sed -i 's/^  server {\n    listen 81;/  server {\n    listen 18081;/' "$CONF" || true

      echo "[openshift] Patched $CONF for unprivileged runtime paths and status port."
    else
      echo "[openshift] WARNING: $CONF not found."
    fi

  nginx-wrapper: |
    #!/bin/sh
    # Force nginx to use the rendered /tmp/nginx.conf
    set -e
    exec /usr/sbin/nginx -c /tmp/nginx.conf "$@"