# Disable Helm Ingress; expose with an OpenShift Route after install
ingress:
  enabled: false

services:
  proxy:
    # Mount entrypoint hooks + nginx wrapper
    extraVolumes:
      - name: nginx-unpriv
        configMap:
          name: budibase-nginx-unpriv
          defaultMode: 0755
    extraVolumeMounts:
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/15-openshift.envsh
        subPath: 15-openshift.envsh
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/80-listen-on-ipv6-by-default.sh
        subPath: 80-listen-on-ipv6-by-default.sh
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/90-openshift-unprivileged.sh
        subPath: 90-openshift-unprivileged.sh
      # Wrapper takes precedence in PATH and forces -c /tmp/nginx.conf
      - name: nginx-unpriv
        mountPath: /usr/local/bin/nginx
        subPath: nginx-wrapper

    # Resource requests/limits (OpenShift requires these)
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  apps:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  worker:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  automationWorkers:
    # enabled defaults to true in chart; keep same sizing as worker by default
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  redis:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"

  objectStore:  # MinIO
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

# CouchDB subchart resources (uses Apache CouchDB chart keys).
# If your OpenShift policy enforces resources on all pods, set them here per the subchart docs:
# https://github.com/apache/couchdb-helm/tree/couchdb-4.3.0/couchdb
# Example (commonly supported in that chart):
couchdb:
  # Main CouchDB container resources (applied by the subchart)
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
  # Backup job resources (already supported by Budibase top-level chart if you enable it)
  # backup:
  #   resources:
  #     requests:
  #       cpu: "50m"
  #       memory: "64Mi"
  #     limits:
  #       cpu: "200m"
  #       memory: "256Mi"