# Disable Ingress (we’ll expose with an OpenShift Route)
ingress:
  enabled: false

services:
  proxy:
    # Mount our hooks, wrapper, and template
    extraVolumes:
      - name: nginx-unpriv
        configMap:
          name: budibase-nginx-unpriv
          defaultMode: 0755
    extraVolumeMounts:
      # Pre-envsubst: set template/output dirs and enable local resolvers
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/05-openshift.envsh
        subPath: 05-openshift.envsh
      # Post-envsubst: remove IPv6 listen if kernel lacks IPv6
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/85-openshift-ipv6-off.sh
        subPath: 85-openshift-ipv6-off.sh
      # Force -c /tmp/nginx.conf without touching the chart’s (broken) args
      - name: nginx-unpriv
        mountPath: /usr/local/bin/nginx
        subPath: nginx-wrapper
      # Our modified template directory
      - name: nginx-unpriv
        mountPath: /opt/bb-templates/nginx.conf.template
        subPath: nginx.conf.template

    # Resource requests/limits (required by OpenShift)
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  apps:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  worker:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  automationWorkers:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  redis:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"

  objectStore:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

# CouchDB subchart resources
couchdb:
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"