# Disable Ingress; use an OpenShift Route instead (instructions below)
ingress:
  enabled: false

services:
  proxy:
    # Mount the unprivileged hooks and wrapper
    extraVolumes:
      - name: nginx-unpriv
        configMap:
          name: budibase-nginx-unpriv
          defaultMode: 0755
    extraVolumeMounts:
      # Pre-envsubst: send output to /tmp and set resolver
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/15-openshift.envsh
        subPath: 15-openshift.envsh
      # Post-envsubst: remove IPv6 listen when IPv6 is unavailable
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/80-listen-on-ipv6-by-default.sh
        subPath: 80-listen-on-ipv6-by-default.sh
      # Post-envsubst: patch pid + temp paths to /tmp
      - name: nginx-unpriv
        mountPath: /docker-entrypoint.d/90-openshift-unprivileged.sh
        subPath: 90-openshift-unprivileged.sh
      # Force nginx to use /tmp/nginx.conf (wrapper masks the real binary in PATH)
      - name: nginx-unpriv
        mountPath: /usr/local/bin/nginx
        subPath: nginx-wrapper

    # Resource requests/limits (required by OpenShift)
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  apps:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  worker:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  redis:
    # If you’re using the bundled Redis
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"

  objectStore:
    # If you’re using the bundled MinIO
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

# CouchDB subchart resources (applied to the Apache CouchDB chart)
# Adjust if your cluster has different quotas. If the subchart rejects these keys,
# consult the subchart docs and move these under the correct field names.
couchdb:
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "2Gi"